name: Go

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -covermode=count ./...
